comment: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: auto
        threshold: 10%
        informational: true
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
