blank_issues_enabled: false
issue_templates:
  - name: "Bug Report"
    description: "Report a bug in the system."
    title: "[Bug]: "
    labels: ["bug"]
    body: "./ISSUE_TEMPLATE/bug_report.yml"
  - name: "Feature request"
    description: "Suggest a new feature or improvement."
    title: "[Feature]: "
    labels: ["enhancement"]
    body: "./ISSUE_TEMPLATE/feature_request.yml"
  - name: "Documentation"
    description: "Suggest updates or additions to documentation."
    title: "[Docs]: "
    labels: ["documentation"]
    body: "./ISSUE_TEMPLATE/documentation.yml"
