name: Documentation
description: Suggest updates or additions to documentation.
title: "[Docs]: "
labels: "documentation"
assignees:
  - ThierryO
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation request!
  - type: textarea
    id: description
    attributes:
      label: Documentation Update
      description: What part of the documentation needs to be updated or added?
      placeholder: What part of the documentation needs to be updated or added?
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: Why is this needed?
      description: Explain the importance of this update.
      placeholder: Explain the importance of this update.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Please describe the proposed solution for this documentation request.
      placeholder: Explain your proposed solution .
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
