on:
  push:
    branches-ignore:
      - gh-pages

name: check-source

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: "Check coding style"
    steps:
      - uses: inbo/actions/check_src@master
        with:
          token: ${{ secrets.pat }}
