on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '6 0 15 * *'
permissions:
  contents: write

name: "check package on main with checklist"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: inbo/actions/check_pkg@v2
