on:
  push:
    branches:
      - master
  schedule:
    - cron: '6 0 * * 1'

name: "check package on master"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    steps:
      - uses: inbo/actions/check_pkg@master
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
          token: ${{ secrets.pat }}
