name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Get tag message
        run: |
          TAG_BODY=$(git tag --contains ${{ github.sha }} -n100 | awk '(NR>1)')
          echo "::set-output name=TAG_BODY::$TAG_BODY"
        id: tag-body
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          body: ${{ steps.tag-body.outputs.TAG_BODY }}
