name: Releases

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows: ["check package on main"]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Get tag message
        run: |
          TAG=$(git tag --contains $(git rev-parse HEAD))
          TAG_BODY=$(git tag --contains $(git rev-parse HEAD) -n100 | awk '(NR>2)')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "TAG_BODY=$TAG_BODY" >> $GITHUB_OUTPUT
        id: tag-body
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tag-body.outputs.TAG }}
          tag: ${{ steps.tag-body.outputs.TAG }}
          body: ${{ steps.tag-body.outputs.TAG_BODY }}
