#' Check the documentation
#' @inheritParams read_checklist
#' @export
check_documentation <- function(x = ".") {
  if (!inherits(x, "Checklist") || !"checklist" %in% x$get_checked) {
    x <- read_checklist(x = x)
  }
  rd_files <- c(
    file.path(x$get_path, "NAMESPACE"),
    list.files(
      file.path(x$get_path, "man"), pattern = "Rd$", full.names = TRUE
    )
  )
  start <- vapply(rd_files, readLines, character(1), n = 1)
  ok <- grepl("roxygen2", start) & grepl("do not edit by hand", start)
  doc_error <- sprintf(
    "Documentation in %s not generated by `roxygen2`", rd_files[!ok]
  )
  x$add_error(doc_error, "documentation")
  return(x)
}
