#' Create an R package according to INBO requirements
#'
#' Creates a package template in a new folder.
#' Use this function when you want to start a new package.
#' Please DO READ `vignette("getting_started")` before running this function.
#'
#' @template checklist_structure
#'
#' @param package Name of the new package.
#' @param path Where to create the package directory.
#' @param title A single sentence with the title of the package.
#' @param description A single paragraph describing the package.
#' @param maintainer The output of [utils::person()] or [`orcid2person()`].
#'   If you use [utils::person()], then you must provide `given`, `family`,
#'   `role`, `email` and  `comment` with valid `ORCID`.
#'   When missing, the functions looks for `usethis.description` in the options.
#'   See [usethis::use_description()] for more information.
#' @param language Language of the project in `xx-YY` format.
#' `xx` is the two letter code for the language.
#' `YY` is the two letter code for the language variant.
#' E.g. `en-GB` for British English, `en-US` for American English, `nl-BE` for
#' Belgian Dutch.
#' @param license What type of license should be used?
#' Choice between GPL-3 and MIT.
#' Default GPL-3.
#' @export
#' @importFrom assertthat assert_that is.string
#' @importFrom fs dir_create dir_ls file_copy is_dir path
#' @importFrom gert git_add git_init
#' @importFrom tools toTitleCase
#' @importFrom utils installed.packages
#' @family setup
#' @examples
#' # maintainer in `utils::person()` format
#' maintainer <- person(
#'   given = "Thierry",
#'   family = "Onkelinx",
#'   role = c("aut", "cre"),
#'   email = "thierry.onkelinx@inbo.be",
#'   comment = c(ORCID = "0000-0001-8804-4216")
#' )
#' # maintainer with `orcid2person()`
#' \dontrun{
#' maintainer <- orcid2person("0000-0001-8804-4216")
#' }
#'
#' # creating the package
#' path <- tempfile()
#' dir.create(path)
#' create_package(
#'   path = path, package = "packagename", title = "package title",
#'   description = "A short description.", maintainer = maintainer,
#'   language = "en-GB", license = "GPL-3"
#' )
create_package <- function(
  package, path = ".", title, description, maintainer, language = "en-GB",
  license = c("GPL-3", "MIT")
) {
  assert_that(
    length(find.package("roxygen2", quiet = TRUE)) > 0,
    msg =
      "Please install the `roxygen2` package. `install.packages(\"roxygen2\")`"
  )
  if (missing(maintainer)) {
    utd <- getOption("usethis.description")
    assert_that(
      has_name(utd, "Authors@R"),
      msg = paste(
        "maintainer not provided and no usethis::use_description defaults",
        "available."
      )
    )
    maintainer <- head(eval(parse(text = utd$"Authors@R")), 1)
  }
  assert_that(inherits(maintainer, "person"))
  assert_that(is_dir(path), msg = sprintf("`%s` is not a directory", path))
  assert_that(is.string(package))
  assert_that(valid_package_name(package))
  path <- path(path, package)
  assert_that(
    !is_dir(path) || length(dir_ls(path, recurse = TRUE)) == 0,
    msg = sprintf("`%s` is not an empty directory", path)
  )
  assert_that(is.string(title))
  validate_language(language)
  license <- match.arg(license)

  dir_create(path)
  repo <- git_init(path = path)
  dir_create(path(path, "R"))

  # add checklist.yml
  x <- checklist$new(x = path, package = TRUE, language = language)
  x$set_ignore(c(".github", "LICENSE.md"))
  write_checklist(x)
  git_add("checklist.yml", repo = repo)

  # create DESCRIPTION
  description <- sprintf(
"Type: Package
Package: %1$s
Title: %2$s
Version: 0.0.0
Authors@R:
  c(%3$s,
    person(given = \"Research Institute for Nature and Forest\",
           role = c(\"cph\", \"fnd\"),
           email = \"info@inbo.be\"))
Description: %4$s
License: %7$s
URL: https://github.com/inbo/%1$s
BugReports: https://github.com/inbo/%1$s/issues
Encoding: UTF-8
Language: %6$s
Roxygen: list(markdown = TRUE)
RoxygenNote: %5$s
",
    package, toTitleCase(title),
    paste(format(maintainer, style = "R"), collapse = "\n"),
    description,
    installed.packages()["roxygen2", "Version"], language,
    license
  )
  writeLines(description, path(path, "DESCRIPTION"))
  tidy_desc(path)
  git_add("DESCRIPTION", repo = repo)

  # create NAMESPACE
  writeLines(
    c("# Generated by roxygen2: do not edit by hand", ""),
    path(path, "NAMESPACE")
  )
  git_add("NAMESPACE", repo = repo)

  # create RStudio project
  file_copy(
    system.file(
      path("package_template", "rproj.template"), package = "checklist"
    ),
    path(path, paste0(package, ".Rproj"))
  )
  git_add(paste0(package, ".Rproj"), repo = repo)

  # add .gitignore
  file_copy(
    system.file(
      path("generic_template", "gitignore"), package = "checklist"
    ),
    path(path, ".gitignore")
  )
  git_add(".gitignore", repo = repo)

  # add .Rbuildignore
  file_copy(
    system.file(
      path("package_template", "rbuildignore"), package = "checklist"
    ),
    path(path, ".Rbuildignore")
  )
  git_add(".Rbuildignore", repo = repo)

  # add codecov.yml
  file_copy(
    system.file(path("package_template", "codecov.yml"), package = "checklist"),
    path(path, "codecov.yml")
  )
  git_add("codecov.yml", repo = repo)

  # add NEWS.md
  news <- sprintf(
    "# %s 0.0.0\n\n* Added a `NEWS.md` file to track changes to the package.",
    package
  )
  writeLines(news, path(path, "NEWS.md"))
  git_add("NEWS.md", repo = repo)

  # add README.Rmd
  readme <- readLines(
    system.file(path("package_template", "README.Rmd"), package = "checklist")
  )
  readme <- gsub("\\{\\{\\{ Package \\}\\}\\}", package, readme)
  writeLines(readme, file.path(path, "README.Rmd"))
  git_add("README.Rmd", repo = repo)

  # add LICENSE.md
  file.copy(
    switch(
      license,
      "GPL-3" = system.file(
        file.path("generic_template", "gplv3.md"), package = "checklist"
      ),
      "MIT" = system.file(
        file.path("generic_template", "mit.md"), package = "checklist"
      )
    ),
    path(path, "LICENSE.md")
  )
  if (license == "MIT") {
    mit <- readLines(file.path(path, "LICENSE.md"))
    mit[3] <- gsub("<YEAR>", format(Sys.Date(), "%Y"), mit[3])
    mit[3] <- gsub("<COPYRIGHT HOLDERS>",
                   "Research Institute for Nature and Forest",
                   mit[3])
    writeLines(mit, file.path(path, "LICENSE.md"))
  }
  git_add("LICENSE.md", repo = repo)

  # Add code of conduct
  dir_create(path(path, ".github"))
  file_copy(
    system.file(
      path("generic_template", "CODE_OF_CONDUCT.md"), package = "checklist"
    ),
    path(path, ".github", "CODE_OF_CONDUCT.md")
  )
  git_add(path(".github", "CODE_OF_CONDUCT.md"), repo = repo)

  # Add contributing guidelines
  file_copy(
    system.file(
      path("package_template", "CONTRIBUTING.md"), package = "checklist"
    ),
    path(path, ".github", "CONTRIBUTING.md")
  )
  git_add(file.path(".github", "CONTRIBUTING.md"), repo = repo)

  # Add GitHub actions
  dir_create(path(path, ".github", "workflows"))
  file_copy(
    system.file(
      path("package_template", "check_on_branch.yml"), package = "checklist"
    ),
    path(path, ".github", "workflows", "check_on_branch.yml"), overwrite = TRUE
  )
  git_add(
    path(".github", "workflows", "check_on_branch.yml"),
    force = TRUE, repo = repo
  )
  file_copy(
    system.file(
      path("package_template", "check_on_main.yml"), package = "checklist"
    ),
    path(path, ".github", "workflows", "check_on_main.yml"), overwrite = TRUE
  )
  git_add(
    path(".github", "workflows", "check_on_main.yml"), repo = repo, force = TRUE
  )
  file_copy(
    system.file(
      path("package_template", "check_on_different_r_os.yml"),
      package = "checklist"
    ),
    path(path, ".github", "workflows", "check_on_different_r_os.yml"),
    overwrite = TRUE
  )
  git_add(
    file.path(".github", "workflows", "check_on_different_r_os.yml"),
    repo = repo, force = TRUE
  )
  file_copy(
    system.file(path("package_template", "release.yml"), package = "checklist"),
    path(path, ".github", "workflows", "release.yml"), overwrite = TRUE
  )
  git_add(
    path(".github", "workflows", "release.yml"), force = TRUE, repo = repo
  )

  # prepare pkgdown
  pkgd <- readLines(
    system.file(path("package_template", "_pkgdown.yml"), package = "checklist")
  )
  pkgd <- gsub("\\{\\{\\{ Package \\}\\}\\}", package, pkgd)
  writeLines(pkgd, path(path, "_pkgdown.yml"))
  git_add("_pkgdown.yml", repo = repo)

  dir_create(path(path, "pkgdown"))
  file_copy(
    system.file(path("package_template", "pkgdown.css"), package = "checklist"),
    path(path, "pkgdown", "extra.css")
  )
  git_add(path("pkgdown", "extra.css"), repo = repo)

  dir_create(path(path, "man", "figures"))
  file_copy(
    system.file(path("package_template", "logo-en.png"), package = "checklist"),
    path(path, "man", "figures", "logo-en.png"), overwrite = TRUE
  )
  git_add(path("man", "figures", "logo-en.png"), force = TRUE, repo = repo)
  file_copy(
    system.file(
      path("package_template", "background-pattern.png"), package = "checklist"
    ),
    path(path, "man", "figures", "background-pattern.png"),
    overwrite = TRUE
  )
  git_add(
    path("man", "figures", "background-pattern.png"), repo = repo, force = TRUE
  )
  file_copy(
    system.file(
      path("package_template", "flanders.woff2"), package = "checklist"
    ),
    path(path, "man", "figures", "flanders.woff2"), overwrite = TRUE
  )
  git_add(file.path("man", "figures", "flanders.woff2"),
                force = TRUE, repo = repo)
  file_copy(
    system.file(
      path("package_template", "flanders.woff"), package = "checklist"
    ),
    path(path, "man", "figures", "flanders.woff"), overwrite = TRUE
  )
  git_add(path("man", "figures", "flanders.woff"), force = TRUE, repo = repo)

  message("package created at `", path, "`")
  return(invisible(NULL))
}

valid_package_name <- function(x) {
  grepl("^[a-zA-Z][a-zA-Z0-9.]+$", x) && !grepl("\\.$", x)
}

#' @importFrom assertthat `on_failure<-`
on_failure(valid_package_name) <- function(call, env) {
  paste(deparse(call$x), "is not a valid package name.")
}
