on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '6 0 15 * *'

name: "check package on main"
permissions:
  contents: write

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: inbo/actions/check_pkg@checklist-0.3.0
