on:
  push:
    branches-ignore:
      - master
      - main
      - ghpages

name: "check package"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
    steps:
      - uses: inbo/actions/check_pkg@checklist-0.3.0
