on:
  push:
    branches-ignore:
      - master
      - ghpages

name: "check package"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    steps:
      - uses: inbo/actions/check_pkg@master
      env:
        CODECOV_TOKEN: {{ secret.CODECOV_TOKEN}}
