name: Releases

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows: ["check package on main with checklist"]
    types:
      - completed

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gettag.outputs.tag }}
      body: ${{ steps.gettag.outputs.body }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        run: |
          git fetch --tags --force
          TAG=$(git tag --contains $(git rev-parse HEAD))
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "body=$TAG_BODY" >> "$GITHUB_OUTPUT"
        id: gettag
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: prepare
    steps:
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{needs.prepare.outputs.tag}}
          tag: ${{needs.prepare.outputs.tag}}
          body: ${{needs.prepare.outputs.body}}
